env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
  #"off" or 0 - turn the rule off
#"warn" or 1 - turn the rule on as a warning (doesn't affect exit code)
#"error" or 2 - turn the rule on as an error (exit code will be 1)
plugins:
  - react
rules:
  indent:
    - off
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - off
    - double
  semi:
    - error
    - always
